name: Security Scan Pipeline

on: [push, pull_request]

jobs:
  security-scans:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Trivy (Container Security Scan)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'bkimminich/juice-shop'
          format: 'table'
          exit-code: 0
          ignore-unfixed: true

      - name: Run OWASP ZAP (Web Security Scan)
        run: |
          docker pull owasp/zap-stable
          docker run --rm -u zap -v $(pwd):/zap/wrk/:rw -t owasp/zap-stable zap-baseline.py -t http://juice-shop:3000 -J zap_report.json
