name: Security Scan Pipeline

on: [push, pull_request]

jobs:
  security-scans:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Trivy (Container Security Scan)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'bkimminich/juice-shop'
          format: 'table'
          exit-code: 0
          ignore-unfixed: true

      - name: Run OWASP ZAP (Web Security Scan)
        uses: zaproxy/action-full-scan@v0.2.0
        with:
          target: 'http://juice-shop:3000'
